version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: movie_rental_db
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: movie_rental
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
